# Light Mode: Everforest Light

# style pane borders
set -g pane-border-style fg=colour8
set -g pane-active-border-style "bg=default fg=colour8"

# style status line
set -g status-bg colour7
set -g status-fg colour0

set -g status-left ""
set -g status-right ""
set -g status-justify left

set-option -g status-position bottom

# Set the color for inactive windows (visible and different from the background)
setw -g window-status-format '#[fg=colour0,bg=colour7] #W '

# Set the color for the active window (clearly distinguishable)
setw -g window-status-current-format '#[fg=colour7,bg=colour2] #W '
